### PR TITLE
TE-8297 strict URL validation

### PR DESCRIPTION
**Pull request by Nidhognit**
- Developer(s): @Nidhognit

- Ticket: https://spryker.atlassian.net/browse/TE-8297

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   Auth                   | patch                 |                       |

-----------------------------------------

##### Change log

Fixes

- Adjusted `RedirectAfterLoginProvider` to make `referer` field validation more strict.
- Adjusted `RedirectAfterLoginEventDispatcherPlugin` to make `referer` field validation more strict.

### CODE REVIEW

**Comment by bezpiatovs** [comment]
changelogs:
> to more strict URL validation taken from referer.

to make `referer` field validation more strict
^ will be better IMO
same around second item

**Review by bezpiatovs — APPROVED** [review]
except remark, test is ok

**Review by asaulenko — APPROVED** [review]

**Review by asmarovydlo — APPROVED** [review]

**Review by gechetspr — APPROVED** [review]
approved

**Comment by dereuromark** [comment]
Whats the status on this one?

**Review by gechetspr — APPROVED** [review]
It was tested on demoshops. All good.

Also code in non deprecated module was tested too.

**Comment by dereuromark** [comment]
Released manually as https://github.com/spryker/auth/releases/tag/3.7.6

**Pull request merged**
